var newWords = [
    ["treat", "заботиться/относиться", "I treat my kids"],
    ["probably", "возможно", "she was probably right"],
    ["pleased", "довольный", "I'm pleased you still remember"],
    ["queue", "очередь", "standing in the queue"],
    ["avoid", "избегать", "We avoid talk"],
    ["mostly", "в основном", "But I mostly did for her"],
    ["during", "в течение", "during these consultations"],
    ["revise", "повторять (слова)", "revise my statement"],
    ["exciting", "захватывающий", "your life was this exciting"],
    ["enjoyable", "приятное", "enjoyable vacation"],
    ["annoyed", "раздраженный", "And I'm annoyed at myself"],
    ["lose his/her/my temper", "выходить из себя", ""],
    ["neighbours", "соседи", "Your neighbours say"],
    ["depend", "зависит от", "It will depend of the physics note"],
    ["suffer", "страдать", "you made me suffer"],
    ["occasionally", "время от времени"],
    ["teases", "дразнить", "a boy teases a girl"],
    ["naughty", "непослушный", "I may have been naughty"],
    ["environment", "окружающая среда", "Her interest was in the environment"],
    ["mess", "беспорядок", "Look at this mess"],
    ["to hold", "держать/проводить", "I never got to hold her"],
    ["excited", "взволнован", "I'm excited about the call"],
    ["fluent", "свободный", "fluent speech"],
    ["inattentive", "невнимательный", "inattentive student"],
    ["prove", "доказывать", "prove a theorem"],
    ["computing", "вычисления", "machine computing"],
    ["extremely", "ооочень", "extremely quick internet"],
    ["certainly", "безусловно", "I will certainly try to help"],

    ["explosion", "взрыв", "night explosion"],
    ["bombardment", "бобмардировка", "aerial bombardment"],
    ["curfew", "комендан час", "curfew from 11 pm"],
    ["quote", "цитата", "''"],
    ["refugees", "беженцы", "refugees in Europe"],
    ["by itself", "оно само", ""],
    ["UNborn", "НЕрожденный", "UNborn child"],
    ["cheer up", "развеселить", "cheer up you"],
    ["pounds", "фунты", ""],

    // ["", "", ""],
    // ["", "", ""],
    // ["", "", ""],
    // ["", "", ""],
];

export {newWords};