var newWords = [
    ["treat", "заботиться/относиться", "I treat my kids"],
    ["probably", "возможно", "she was probably right"],
    ["pleased", "довольный", "I'm pleased you still remember"],
    ["queue", "очередь", "standing in the queue"],
    ["avoid", "избегать", "We avoid talk"],
    ["mostly", "в основном", "But I mostly did for her"],
    ["during", "в течение", "during these consultations"],
    ["revise", "повторять (слова)", "revise my statement"],
    ["exciting", "захватывающий", "your life was this exciting"],
    ["enjoyable", "приятное", "enjoyable vacation"],
    ["annoyed", "раздраженный", "And I'm annoyed at myself"],
    ["lose his/her/my temper", "выходить из себя", ""],
    ["neighbours", "соседи", "Your neighbours say"],
    ["depend", "зависит от", "It will depend of the physics note"],
    ["suffer", "страдать", "you made me suffer"],
    ["occasionally", "время от времени"],
    ["teases", "дразнить", "a boy teases a girl"],
    ["naughty", "непослушный", "I may have been naughty"],
    ["environment", "окружающая среда", "Her interest was in the environment"],
    ["mess", "беспорядок", "Look at this mess"],
    ["to hold", "держать/проводить", "I never got to hold her"],
    ["excited", "взволнован", "I'm excited about the call"],
    ["fluent", "свободный", "fluent speech"],
    ["inattentive", "невнимательный", "inattentive student"],
    ["prove", "доказывать", "prove a theorem"],
    ["computing", "вычисления", "machine computing"],
    ["extremely", "ооочень", "extremely quick internet"],
    ["certainly", "безусловно", "I will certainly try to help"],

    ["explosion", "взрыв", "night explosion"],
    ["bombardment", "бобмардировка", "aerial bombardment"],
    ["curfew", "комендан час", "curfew from 11 pm"],
    ["quote", "цитата", "''"],
    ["refugees", "беженцы", "refugees in Europe"],
    ["by itself", "оно само", ""],
    ["UNborn", "НЕрожденный", "UNborn child"],
    ["cheer up", "развеселить", "cheer up you"],
    ["pounds", "фунты", ""],

    ["chorus", "припев", "Sing along with me, this is the chorus"],
    ["flop", "провал", "the movie will be a flop"],
    ["lurics", "текст песни", "Who knows the lyrics"],

    ["knife", "нож", "sharp knife"],
    ["towel", "полотенце", "beach towel"],
    ["flour", "мука", "rice flour"],
    ["drop", "падать", ""],
    ["laziness", "лень", ""],
    ["graduate", "выпускник", "school graduate"],
    ["couple", "пара/несколько", "couple of years ago"],

    ["I would like", "я хотела бы", ""],
    ["attitude to", "отношение", "my attitude to life "],
    ["treasure", "сокровище", "treasure map"],
    ["thirsty", "жаждущий", "the tourists were hot and thirsty"],

    ["charity", "благодтворительность", "money for charity"],
    ["poverty", "бедность", "poverty line"],
    ["earn", "зарабатывать", "they earn $35 per hour"],
    ["barefoot", "босиком", "barefoot on the grass"],
    ["poor", "бедный", "very poor diet"],
    ["jeweller", "ювелир", ""],
    ["perfomer", "выступающий", "a circus performer"],

    ["however", "однако", ""],
    ["furniture", "мебель", "wooden furniture"],
    ["experience", "опыт", "good experience"],
    ["terrible", "ужасный", "terrible conditions "],
    ["huge", "огромный", "huge cake"],
    ["determination", "решимость/определение", ""],
    ["decided", "решенный", "decided cases"],
    ["passing", "прохождение", "passing the game"],

    ["both", "оба", ""],
    ["stomachache", "боль в животе", ""],
    ["cabbage", "капуста", "cabbage soup"],
    ["recently", "недавно", "recently woke up"],
    
    // ["", "", ""],
    // ["", "", ""],
    // ["", "", ""],
    // ["", "", ""],
];

export { newWords };
